### ISSUE TITLE
TLS Close

### ISSUE THREAD

**Issue by krixano** [pitr/gig#6]
I'm posting this issue just to make it know that improper TLS close is an issue in Geminispace, in case you might need to make sure gig does this properly.

https://gitlab.com/gemini-specification/protocol/-/issues/2

**Comment by pitr** [comment]
There's already a `crypto/tls.Conn.Close()` call [here](https://github.com/pitr/gig/blob/f807ab942b0b66f03d60a9a2b25e172beaa86019/gig.go#L524). Let me know if this is not enough.

**Comment by krixano** [comment]
I only posted this to make sure the close is happening. I didn't read any of the code because I don't know enough about how any of this works.
If you are properly closing for everything as per the new changes to the Gemini spec, then this issue can be closed.

**Comment by krixano** [comment]
Also, according to the statistics given in the issue I linked about this, most servers don't do the close on only *some* pages and not others.

**Comment by pitr** [comment]
I searched dump2.json included in that ticket for my services (ones using gig) and they all have `"short_read": false`. I am not sure whether that means they send tls close or not.

**Comment by ghost** [comment]
I have just checked with portal.mozz.us that gig *is* closing the connections correctly for my server. So I think Gig should be fine with this.

**Comment by ghost** [comment]
I'm actually going to reopen this issue, because it looks like the close_notify isn't being sent on the notfound error: 
![image](https://user-images.githubusercontent.com/4098042/141713755-7fd51615-ef17-43a0-af8f-c45fda8f66e2.png)

It's possible this is happening for other errorcodes, I haven't tested yet.

I do want to note that every single server I've tested (and I've tested like 20 of them) with agunua has had this same problem. So I have mentioned on the mailing list about it possibly being an agunua problem (it reporting things incorrectly).

**Comment by pitr** [comment]
@krixano in the mailing list you mentioned that the successful responses close TLS correctly, is that right? This will help identify the bug

**Comment by ghost** [comment]
I've tested with a different tool (openssl s_client), and it looks like the problem was with Agunua not reporting things correctly, not with Gig Framework. You can see here that on a nonexistant page that sends a not found error, it *does* send the close_notify. (Also, yes, Gig also sends the close_notify with successful responses as well).

I also looked through the code prior to this just to see if I saw anything out of place, but afaik, I didn't.

I will close this, but if we need to reopen it at a later time, then that can always be done.

![image](https://user-images.githubusercontent.com/4098042/141792575-759febe8-52a0-4679-b85a-36b6c753ffb8.png)
